### ISSUE TITLE
Prepare provider for release

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi-linode#3]
In order to get this provider prepared for release there are a few things we need to ensure we:

- [x] Depend on the most recent release of the upstream Terraform provider and have mapped all data sources and resources which make sense.
- [x] ~~Have the various configuration options for the provider listed in the README file such that package consumers can easily find them.~~ It's enough to have the link to the reference docs in the README, I think.
- [x] Have documentation ready to publish (in the `pulumi/docs` repo)
- [x] Have at least one example running in CI against the provider
- [x] Nominate maintainers

I think we're there with 1 and 3, and have an account set up for 4 - that just needs configuring in Travis CI. @displague - as the person driving this from Linode, could you address 2 and 5, please?

**Comment by displague** [comment]
https://help.github.com/en/articles/about-code-owners could be useful for this too.

@ctreatma and @displague make sense for initial maintainers. 
@linode/3pt should perpetually include everyone.

I based the README on the other providers.  Is there a template to follow in terms of another provider that already includes the 'configuration options'?

**Comment by lukehoban** [comment]
> https://help.github.com/en/articles/about-code-owners could be useful for this too.

Great idea - let's add a `CODEOWNERS` here.

**Comment by jen20** [comment]
I've just finished updating the provider to use Go Modules, target the latest upstream provider, and got examples running in CI.

**Comment by jen20** [comment]
OK, this all looks good to go. I'll tag a release now - v0.18.0 to keep broadly in line with the other packages - and update the docs sites to include this.

**Comment by displague** [comment]
I also added an example in the examples project: https://github.com/pulumi/examples/pull/295
